version: '3'

services:
  zookeeper:
    image: wurstmeister/zookeeper
    container_name: zookeeper
    ports:
    - 2181:2181

  kafka:
    image: wurstmeister/kafka
    container_name: kafka
    ports:
    - 9092:9092
    environment:
      KAFKA_ADVERTISED_HOST_NAME: localhost
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181

  db:
    image: mysql:latest
    container_name: MySQLES2
    restart: always
    environment:
      MYSQL_DATABASE: stockz
      MYSQL_ROOT_PASSWORD: admin
    ports:
    - 3306:3306

#  lab-proj:
#    build: .
#    container_name: stocktracking
#    depends_on:
#      - zookeeper
#      - kafka
#      - db
#    ports:
#    - 8080:8080
#    environment:
#      SPRING_DATASOURCE_URL: jdbc:mysql://localhost:3306/stockz?useSSL=false