package com.example.stocktracking;

import com.example.stocktracking.models.Stock;
import com.example.stocktracking.models.StockTable;
import com.example.stocktracking.models.StockTableRepository;

import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Controller;
import org.springframework.web.bind.annotation.GetMapping;
import org.springframework.web.bind.annotation.PostMapping;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RequestParam;
import org.springframework.web.bind.annotation.ResponseBody;

import java.util.ArrayList;

@Controller // This means that this class is a Controller
@RequestMapping(path="/demo") // This means URL's start with /demo (after Application path)
public class MainController {
    @Autowired // This means to get the bean called StockTableRepository
    // Which is auto-generated by Spring, we will use it to handle the data
    private StockTableRepository StockTableRepository;

    @PostMapping(path="/add") // Map ONLY POST Requests
    public @ResponseBody String addNewStockTable (@RequestParam String name
            , @RequestParam double email) {
        // @ResponseBody means the returned String is the response, not a view name
        // @RequestParam means it is a parameter from the GET or POST request

        StockTable n = new StockTable();
        n.setSymbol(name);
        n.setValue(email);
        StockTableRepository.save(n);
        return "Saved";
    }

    @GetMapping(path="/all")
    public @ResponseBody Iterable<StockTable> getAllStockTables() {
        // This returns a JSON or XML with the StockTables
        return StockTableRepository.findAll();
    }

//    public void insertStocks(ArrayList<Stock> lista){
//        for(int i=0;i<lista.size();i++){
//            Stock a= lista.get(0);
////            double per=(double) a.getPercent().replace("%","");
//            StockTableRepository.save(new StockTable(a.getSymbol(), a.getPrice(), a.getPreviousClose()));
//        }
//    }
}